name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  google_maps_flutter: ^2.10.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  shared_preferences: ^2.5.4
  json_annotation: ^4.9.0
  uuid: ^4.5.2
  image_picker: ^1.2.1
  firebase_storage: ^12.4.10
  geocoding: ^4.0.0
  geolocator: ^14.0.0
  table_calendar: ^3.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
